[WIP] feat(charts): Add log forwarding to Azure Log Analytics
Azure/osm-azure pull request #12
Opened 2020-10-26 22:07 UTC by SanyaKochhar

Adds log processing and forwarding of error level logs to Azure Log Analytics using Fluent Bit

2020-10-28 23:37 UTC, ksubrmnn requested changes

2020-10-28 23:37 UTC, ksubrmnn commented on docs/logs.md
> +[Fluent Bit](https://fluentbit.io/) is an open source log processor and forwarder which allows you to collect data/logs and send them to multiple destinations. OSM provides log forwarding by optional
Can you explicitly state that it is deployed by default?

2020-10-29 18:15 UTC, ritazh approved these changes
lgtm

2020-10-30 15:18 UTC, ksubrmnn approved these changes

2020-10-30 15:25 UTC, merged