Fix Sec Vuln 2021_3995_3996
Azure/osm-azure pull request #137
Opened 2022-01-25 22:19 UTC by nshankar13

Signed-off-by: nshankar13 <nshankar@microsoft.com>

**Description**: Fix security vulnerabilities CVE 2021 3995 and 3996 in osm-helm-cli image

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Networking             [ ]
- Metrics                [ ]
- Security               [X]
- Tests                  [ ]
- CI System              []
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

2022-01-25 22:22 UTC, trstringer requested changes

2022-01-25 22:22 UTC, trstringer commented on tools/helm/Dockerfile
> +RUN clean-install jq curl ca-certificates libssl1.1 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libgmp10 bsdutils
Can you make a quick comment/note here like in line 10 explaining the upgrade?

2022-01-25 23:00 UTC, trstringer approved these changes

2022-01-26 17:34 UTC, SanyaKochhar approved these changes

2022-01-26 17:35 UTC, merged