Update version to v1.0.0.1
Azure/osm-azure pull request #147
Opened 2022-03-23 17:48 UTC by nshankar13

Signed-off-by: nshankar13 <nshankar@microsoft.com>

**Description**: Update osm-arc version to v1.0.0.1

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Networking             [ ]
- Metrics                [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

2022-03-23 18:24 UTC, trstringer requested changes

2022-03-23 18:24 UTC, trstringer commented on charts/osm-arc/Chart.yaml
> +version: 1.0.0.1
This format is not [valid semver](https://semver.org/). I think we'll likely have to do something like `1.0.0-1`.

2022-03-23 19:21 UTC, nshankar13 commented
/azp run upgrade-e2e-arc

2022-03-24 15:31 UTC, SanyaKochhar approved these changes

2022-03-24 17:16 UTC, trstringer approved these changes

2022-03-24 17:25 UTC, merged