Restructured Chart
Azure/osm-azure pull request #18
Opened 2020-11-12 16:39 UTC by nshankar13

Separated this chart into two new ones: osm-arc and osm. OSM is a dependency of osm-arc, and osm-arc values will override those in the values.yaml of osm. Osm-arc will have templates, such as osm-label, that are specific for arc environments. 

Now the workflow for installing the chart via helm will look something like this: 

`
helm dependency update osm-arc
helm install osm osm-arc --namespace arc-osm-system
`

2020-11-12 22:50 UTC, ritazh commented on Makefile
> +	./.staging/helm/linux-amd64/helm install osm ./charts/osm-arc --namespace arc-osm-system
```suggestion
	./.staging/helm/linux-amd64/helm install osm ./charts/osm-arc --namespace arc-osm-system --dependency-update
```

2020-11-12 22:50 UTC, ritazh commented on Makefile
> +	./.staging/helm/linux-amd64/helm dependency update ./charts/osm-arc
you can remove this

2020-11-12 22:57 UTC, ritazh commented on Makefile
>  test-e2e:
We should add a new Makefile target similar to this [example](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/Makefile#L130-L139). We can run this target before cutting a release of osm-arc to ensure the osm chart has been updated and included as part of the new release of osm-arc chart.

2020-11-12 23:00 UTC, ritazh commented on charts/osm-arc/Chart.yaml
> +description: A Helm chart for Kubernetes
```suggestion
description: A Helm chart to install the OSM control plane on Azure Arc enabled Kubernetes clusters.
```

2020-11-12 23:05 UTC, ritazh commented on charts/osm-arc/Chart.yaml
> +  repository: "file://../../charts/osm"
Should this be https://github.com/openservicemesh/osm/tree/main/charts/osm?

2020-11-12 23:07 UTC, ritazh commented on charts/osm-arc/Chart.yaml
> +version: 0.5.0
The value here should match the osm-arc tgz file generated.

2020-11-12 23:11 UTC, ritazh commented on charts/osm/Chart.yaml
I think you can add all the charts/osm files to gitignore

2020-11-12 23:14 UTC, ritazh commented on charts/osm-arc/Chart.lock
> +  repository: file://../../charts/osm
Should this be https://github.com/openservicemesh/osm/tree/main/charts/osm?

2020-11-12 23:16 UTC, ritazh commented on charts/osm-arc/values.yaml
> +      registry: "mcr.microsoft.com/oss/fluent"
You also need to update the [envoy image](https://github.com/openservicemesh/osm/blob/main/charts/osm/values.yaml#L11) and the [osm-controller image](https://github.com/openservicemesh/osm/blob/main/charts/osm/values.yaml#L6-L7).

2020-11-12 23:23 UTC, ritazh commented on charts/values-override.yaml
> +# Default values for osm.
This file should be values.yaml.

2020-11-13 00:52 UTC, ritazh commented on charts/osm-arc/Chart.yaml
> +  repository: "file://../../charts/osm"
@michelleN I noticed we dont have index.yaml in https://github.com/openservicemesh/osm/tree/main/charts/osm is that going to be an issue finding older versions of the osm chart?

2020-11-13 01:06 UTC, michelleN requested changes
Could you split this into separate PRs? The first PR being the one that creates the `osm-arc` chart with no dependency so we can review that separately.

2020-11-19 17:02 UTC, michelleN approved these changes

2020-11-19 22:53 UTC, ritazh commented on .gitignore
> +charts/osm/charts
this should be `charts/osm-arc/charts` as you want to ignore the dependency chart in the new osm-arc chart. please also `git rm charts/osm-arc/charts` as you currently have those files checked in.

2020-11-19 22:57 UTC, ritazh commented on test/bats/test.bats
> +    run wait_for_process $WAIT_TIME $SLEEP_TIME "kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io osm-webhook-osm"
please open an issue in this repo to update this after the dependent chart has been updated to 0.5.1

2020-11-19 23:01 UTC, ritazh commented on charts/osm-arc/values.yaml
> +      registry: "mcr.microsoft.com/oss/fluent"
Still missing the envoy image

2020-11-19 23:03 UTC, ritazh commented on charts/osm-arc/values.yaml
> +    customerID: 49a4d43a-81ef-4607-83f6-a13872c6ae60
You should include these new fields in this values.yaml _after_ the osm dependency chart has been upgraded to 0.5.1 as they dont exist in 0.5.0 right?

2020-11-19 23:17 UTC, ritazh commented on Makefile
>  test-e2e:
created https://github.com/Azure/osm-azure/issues/21

2020-11-20 01:34 UTC, ritazh approved these changes
lgtm

2020-11-20 01:37 UTC, ritazh commented
cc @snehachhabria @SanyaKochhar PTAL

2020-11-20 06:52 UTC, snehachhabria approved these changes

2020-11-20 17:06 UTC, SanyaKochhar approved these changes

2020-11-20 17:07 UTC, merged